itinerary_compilation_task:
  description: >
    # Travel Planning AI Agent Task Description

    ## Primary Objective
    Create a detailed, personalized travel itinerary by researching activities, events, and attractions in specified cities, then optimally distributing time across locations based on available opportunities and traveler preferences.

    ## Input Parameters
    - Country: {country}
    - Cities: {cities} (list of cities to visit)
    - Date Range: {date_range} (overall trip duration)
    - Traveler Age: {age}
    - Traveler preferences: {preferences}

    ## Core Tasks

    ### 1. Research Phase
    - City-specific research: For each city, gather comprehensive information about:
      - Current events and festivals during the travel period
      - Popular attractions and landmarks
      - Age-appropriate activities and entertainment
      - Local experiences and cultural highlights
      - Seasonal considerations and weather-dependent activities

    - Information gathering methods:
      - Use web search tools to find current events, attractions, and activities
      - Scrape relevant websites for detailed information
      - Cross-reference multiple sources for accuracy
      - Identify time-sensitive events (concerts, festivals, exhibitions)

    ### 2. Analysis Phase
    - Interest matching: Analyze gathered information to identify activities that align with the traveler's age group and likely interests
    - Time optimization: Determine how many days each city warrants based on:
      - Number and significance of available activities
      - Special events occurring during the travel window
      - Seasonal factors affecting accessibility
      - Travel logistics between cities

    ### 3. Planning Phase
    - Date allocation: Distribute the total travel days across cities to maximize experience value
    - Itinerary creation: Develop a day-by-day schedule including:
      - Specific dates for each city
      - Recommended activities with timing
      - Must-see attractions prioritized by relevance
      - Backup options for weather-dependent activities
      - Each day in the trip should be planned
  expected_output: >
    Deliver a comprehensive travel plan containing:
    - City-by-city breakdown with allocated dates
    - Daily itineraries with specific activities and timing


city_explorer_task:
  description: >
    Find and catalog must-see landmarks, world-class museums, iconic attractions, and unique local experiences in the target city.
    Research opening hours, ticket prices, and accessibility information for each location. Prioritize attractions based on cultural significance, popularity, and alignment with traveler age group.

    ## Input Parameters
    - Country: {country}
    - Cities: {cities} (list of cities to visit)
    - Date Range: {date_range} (overall trip duration)
    - Traveler Age: {age}
    - Traveler preferences: {preferences}
  expected_output: >
    A comprehensive list of 10-15 top attractions including landmarks, museums, and local experiences.
    Each entry should include name, brief description, estimated visit duration, and practical details like opening hours and admission costs. Results should be ranked by importance and suitability for the traveler's profile.


events_scout_task:
  description: >
    Research current and upcoming events, festivals, concerts, exhibitions, and seasonal activities happening during the specified travel dates.
    Focus on events that match the traveler's age group and interests. Verify dates, venues, and ticket availability for time-sensitive opportunities.

    ## Input Parameters
    - Country: {country}
    - Cities: {cities} (list of cities to visit)
    - Date Range: {date_range} (overall trip duration)
    - Traveler Age: {age}
    - Traveler preferences: {preferences}
  expected_output: >
    A chronological list of relevant events with specific dates, times, venues, and ticket information. Include both free and paid events, highlighting unique or limited-time opportunities.
    Provide booking links and advance purchase recommendations where applicable.


restaurants_scout_task:
  description: >
    Identify highly-rated restaurants, local food specialties, and distinctive dining experiences that showcase the city's culinary scene.
    Research reservation requirements, price ranges, and dietary accommodation options. Include a mix of fine dining, casual local favorites, and must-try street food or markets.

    ## Input Parameters
    - Country: {country}
    - Cities: {cities} (list of cities to visit)
    - Date Range: {date_range} (overall trip duration)
    - Traveler Age: {age}
    - Traveler preferences: {preferences}
  expected_output: >
    A curated selection of 8-12 dining recommendations across different price points and cuisine types.
    Each recommendation should include restaurant name, specialty dishes, price range, and reservation details. Include local food markets, iconic dishes, and dining experiences unique to the destination.


itinerary_compilation_task_seq:
  description: >
    ## Primary Objective
    Create a detailed, personalized travel itinerary by Synthesizing activities, events, and attractions in specified cities,
    then optimally distributing time across locations based on available opportunities and traveler preferences.

    ## Input Parameters
    - Country: {country}
    - Cities: {cities} (list of cities to visit)
    - Date Range: {date_range} (overall trip duration)
    - Traveler Age: {age}
    - Traveler preferences: {preferences}

    Ensure that itinerary follows travelers preferences and dates.
  expected_output: >
    A detailed daily itinerary with specific times, locations, and activities for each day of the trip. 
    Include travel time between locations, meal breaks, and buffer time for unexpected delays.


flight_search_task:
  description: >
    Research and find optimal flight options for the traveler's route, considering departure/arrival cities, travel dates, and budget preferences.
    Compare airlines, flight times, layovers, and pricing across multiple booking platforms. Identify the best balance between cost, convenience, and travel time for the specific itinerary.
    Trip itinerary: {itinerary}

    # Instructions
    - Decompose itinerary to separate flights, e.g. origin -> destination_1 -> destination_2 -> origin
    - Use tool to search for the each flight
    - Aggregate information to provide general flights plan
  expected_output: >
    A complete flight plan with recommended outbound and return flights including specific flight numbers, airlines, departure/arrival times, and gate information.
    Include inter-city flights if traveling between multiple destinations.
    Provide booking links, total travel costs, and step-by-step instructions for purchasing tickets.


